language: python
python:
- '3.6'
before_install:
- sudo apt-get install gfortran
install:
- pip install -r requirements.txt
- pip install coverage codacy-coverage
script:
- coverage run setup.py test
- coverage xml
- python-codacy-coverage

