language: python
python:
- '3.6'
env:
  global:
    secure: p6NczH/g5GogBrnoSx8xitlMJ3zMgi5+fR3AUcxs7XodxMCJNnnJbKfSEQpiLmoJAbEXk5GO6UxsPaT1lf38UbBpjOnJDe8Pzs+gCIr0L8i4J4C2eMcvAimmj7fVqWfdCOwIWtCuqJiXig13Nzmkj9jZ/0CyHIrTt4fg/6maSjF8zQ+Nw8s6oT84vcjHjkFb/B4B1tEi7AWMSEKNR9S/2Eb8fNd9bSejzZNYMGk3A/oxjtJWLMn26rl/fZ1ZVBl2E50fDOMDb/RrF1vKipFbKQy3begZFcNOMlIzByW7XwAj5LPaDAnZoSvV9CwLZTAjgF9p8I4Zs6ccE62d3RkSOdwYU9t6AEQsuKIEdnOaFUuMV1zxrURDVyRJ1lDaMx2FCarfkmN30rP86FsYbDnK1HIs40oYfrjr5W/4J4ulcV03h9af3xMusXR4HbUkpZ5o4jeJCYinyVbyfPENo3TS96HZc4BXkW15dyCEEhiA1sWcwpicFH0z+ws/16kvJvTLe8VxW9xTlnO4Y5t7i/GeIOugUDOuX32k7JsPJhsORYUl0d3kGv/TtLkszv6MDpM2QQX/JEWObhnmdhz2jY9VTu7SNRFEGk+K5k1IOf8SFk6HT1jP9FRL1SbVruEC3Wv4djZ8urDE0fQ0NayNO4WZwQaKftUpMnP6GgH4U/B1GwU=
before_install:
- sudo apt-get install gfortran
install:
- pip install -r requirements.txt
- pip install coverage codacy-coverage
script:
- coverage run setup.py test
- coverage xml
- python-codacy-coverage -r coverage.xml

